---
version: '3.7'
services:
  sermon:
    container_name: sermon
    image: tborychowski/sermon
    restart: unless-stopped
    ports:
      - "3010:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./data:/app/data
      - ./config.json:/app/data/config.json:ro

      - /proc:/app/data/proc:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/os-release:/app/data/os-release:ro
      - /sys/class/thermal/thermal_zone0/temp:/app/data/temp:ro

      # disks
      - /:/mnt/root:ro
      - /mnt/backup:/mnt/backup:ro
      - /mnt/store:/mnt/store:ro
      - /mnt/media:/mnt/media:ro
