---
version: '3.7'
services:
  sermon:
    container_name: sermon
    image: tborychowski/sermon
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - /etc/localtime:/etc/localtime:r
      - /proc/cpuinfo:/app/proc/cpuinfo:r
      - /proc/loadavg:/app/proc/loadavg:r
      - /proc/meminfo:/app/proc/meminfo:r
      - /etc/os-release:/app/proc/os-release:r
      - /sys/class/thermal/thermal_zone0/temp:/app/proc/temp:r
      - /proc/uptime:/app/proc/uptime:r
      - ./config.json:/app/config.json:r
